name: universal_pck_audio_extractor
description: Multi platform, Multi core, Multi format, Audio Converter for .pck files into various workable files, written in dart!
version: 0.1.0
homepage: https://github.com/yoroshikun/universal_pck_audio_extractor/

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  dcli: ^0.37.0
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
